# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QScollAeraExample.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Scoll(object):
    def setupUi(self, Scoll):
        Scoll.setObjectName("Scoll")
        Scoll.resize(811, 356)
        self.formLayout = QtWidgets.QFormLayout(Scoll)
        self.groupBox = QtWidgets.QGroupBox("Group of something")
        self.labelList = []
        self.comboList = []
        for i in range(10):
            self.labelList.append(QtWidgets.QLabel("Label"))
            self.comboList.append(QtWidgets.QPushButton("Click Me"))
            self.formLayout.addRow(self.labelList[i], self.comboList[i])
        self.groupBox.setLayout(self.formLayout)
        scroll = QtWidgets.QScrollArea()
        scroll.setWidget(self.groupBox)
        scroll.setWidgetResizable(True)
        scroll.setFixedHeight(400)
        layout = QtWidgets.QVBoxLayout()
        layout.addWidget(scroll)
        self.retranslateUi(Scoll)
        QtCore.QMetaObject.connectSlotsByName(Scoll)



    def retranslateUi(self, Scoll):
        _translate = QtCore.QCoreApplication.translate
        Scoll.setWindowTitle(_translate("Scoll", "Dialog"))
