# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QDialExample.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QDialExample(object):
    def setupUi(self, QDialExample):
        QDialExample.setObjectName("QDialExample")
        QDialExample.resize(600, 287)
        font = QtGui.QFont()
        font.setPointSize(20)
        QDialExample.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/cut.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QDialExample.setWindowIcon(icon)
        self.dial = QtWidgets.QDial(QDialExample)
        self.dial.setGeometry(QtCore.QRect(40, 50, 261, 171))
        self.dial.setProperty("value", 40)
        self.dial.setObjectName("dial")
        self.label = QtWidgets.QLabel(QDialExample)
        self.label.setGeometry(QtCore.QRect(340, 100, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")

        self.retranslateUi(QDialExample)
        QtCore.QMetaObject.connectSlotsByName(QDialExample)

        self.dial.valueChanged.connect(self.valuePrint)

    def retranslateUi(self, QDialExample):
        _translate = QtCore.QCoreApplication.translate
        QDialExample.setWindowTitle(_translate("QDialExample", "Dialog"))
        self.label.setText(_translate("QDialExample", "Value is :"))

    def valuePrint(self):
        value = self.dial.value()
        self.label.setText("Value is :" + str(value))
