# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToolBarExample.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 137)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCopy = QtWidgets.QMenu(self.menubar)
        self.menuCopy.setObjectName("menuCopy")
        self.menuSave = QtWidgets.QMenu(self.menubar)
        self.menuSave.setObjectName("menuSave")
        self.menuPaste = QtWidgets.QMenu(self.menubar)
        self.menuPaste.setObjectName("menuPaste")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCopy.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuPaste.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuFile.setWindowIcon(QIcon("Resources/new.jpg"))
        self.menuCopy.setTitle(_translate("MainWindow", "Copy"))
        self.menuCopy.setWindowIcon(QIcon("Resources/copy.png"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuSave.setWindowIcon(QIcon("Resources/save.png"))
        self.menuPaste.setTitle(_translate("MainWindow", "Paste"))
        self.menuPaste.setWindowIcon(QIcon("Resources/paste.jpg"))
