# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProgressBarExample.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QThread, pyqtSignal
import time

class MyThread(QThread):
    # Create a counter thread
    change_value = pyqtSignal(int)
    def run(self):
        cnt = 0
        while cnt <= 100:
            cnt+=1
            time.sleep(0.3)
            self.change_value.emit(cnt)

class Ui_progressBar(object):
    def setupUi(self, progressBar):
        progressBar.setObjectName("progressBar")
        progressBar.resize(668, 195)
        self.progressBar_2 = QtWidgets.QProgressBar(progressBar)
        self.progressBar_2.setGeometry(QtCore.QRect(100, 70, 481, 21))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton = QtWidgets.QPushButton(progressBar)
        self.pushButton.setGeometry(QtCore.QRect(100, 120, 161, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(progressBar)
        QtCore.QMetaObject.connectSlotsByName(progressBar)
        self.pushButton.clicked.connect(self.startProgressBar)

    def retranslateUi(self, progressBar):
        _translate = QtCore.QCoreApplication.translate
        progressBar.setWindowTitle(_translate("progressBar", "Dialog"))
        self.pushButton.setText(_translate("progressBar", "Start Download"))

    def startProgressBar(self):
        self.thread = MyThread()
        self.thread.change_value.connect(self.setProgressVal)
        self.thread.start()

    def setProgressVal(self, val):
        self.progressBar_2.setValue(val)
