# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ButtonGroup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(571, 300)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(170, 100, 371, 80))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(60, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 30, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 30, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 120, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton.clicked.connect(self.print)
        self.pushButton_2.clicked.connect(self.print)
        self.pushButton_3.clicked.connect(self.print)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Button Group"))
        self.groupBox.setTitle(_translate("Form", "Language"))
        self.pushButton.setText(_translate("Form", "C++"))
        self.pushButton_2.setText(_translate("Form", "Python"))
        self.pushButton_3.setText(_translate("Form", "C"))
        self.label.setText(_translate("Form", "You choice :"))

    def print(self):
        if (self.pushButton.clicked):
            self.label.setText(self.pushButton.text())
        if (self.pushButton_2.clicked):
            self.label.setText(self.pushButton_2.text())
        if (self.pushButton_3.clicked):
            self.label.setText(self.pushButton_3.text())